plugins {
	id "dev.architectury.loom" version "1.9-SNAPSHOT"
	id 'maven-publish'
	id "com.hypherionmc.modutils.modpublisher" version "2.+"
}

base {
	archivesName = project.archives_base_name
}

version = "$project.mod_version+$project.upstream_version+$project.minecraft_version"
group = project.maven_group

sourceSets {
	javadoc {
	}

	testMod {
		compileClasspath += main.compileClasspath
		runtimeClasspath += main.runtimeClasspath
	}
}

loom {
	forge {
		mixinConfigs = [
			"mixins.libgui.json"
		]
	}
	createRemapConfigurations(sourceSets.testMod)

	runs {
		testModClient {
			client()
			forgeTemplate "client"
			ideConfigGenerated true
			name = "TestModClient"
			mods {
				create("libgui_test") {
					sourceSet(sourceSets.testMod)
				}

				create("libgui"){
					sourceSet sourceSets.main
				}
			}
			source sourceSets.testMod
		}

		testModServer {
			server()
			name = "TestModServer"
			ideConfigGenerated true
			mods {
				create("libgui_test") {
					sourceSet(sourceSets.testMod)
				}

				create("libgui"){
					sourceSet sourceSets.main
				}
			}
			source sourceSets.testMod
		}
	}
}

repositories {
	maven {
		url "https://server.bbkr.space/artifactory/libs-release"
		content {
			includeGroup "io.github.cottonmc"
		}
	}
	maven { url "https://jitpack.io" }
	maven { url "https://maven.su5ed.dev/releases" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"

	forgeRuntimeLibrary(implementation(include("blue.endless:jankson:1.2.3")))

	include api("com.github.TexBlock:LibNinePatch:master-SNAPSHOT")
	forgeRuntimeLibrary("com.github.TexBlock:LibNinePatch:master-SNAPSHOT")

	// Test mod dependencies
	testModImplementation sourceSets.main.output
}

processResources {
	inputs.property "version", project.version

	filesMatching("META-INF/mods.toml") {
		expand "version": project.version
	}
}

java {
	withSourcesJar()
	withJavadocJar()

	toolchain.languageVersion = JavaLanguageVersion.of(17)

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile) {
	// ensure that the encoding is set to UTF-8, no matter what the system default is
	// this fixes some edge cases with special characters not displaying correctly
	// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
	options.encoding = "UTF-8"
	options.release = 17
}

jar {
	from "CREDITS.txt", "LICENSE"
}

def javadocBuildJar = tasks.register('javadocBuildJar', Jar) {
	destinationDirectory = file('build/devlibs')
	archiveClassifier = 'javadoc-build'
	from sourceSets.javadoc.output
}

javadoc {
	dependsOn javadocBuildJar

	options {
		links 'https://javadoc.io/doc/org.jetbrains/annotations/19.0.0'
		taglets 'io.github.cottonmc.cotton.gui.jd.ExperimentalTaglet',
			'io.github.cottonmc.cotton.gui.jd.PropertyTaglet'
		tagletPath javadocBuildJar.get().archiveFile.get().asFile
	}

	exclude("**/impl/**")
}

publisher {
	apiKeys.modrinth(System.getenv("MODRINTH_TOKEN"))
	apiKeys.curseforge(System.getenv("CURSEFORGE_TOKEN"))

	curseID = "$project.curseforge_id"
	modrinthID = "$project.modrinth_id"
	versionType = "alpha"
	changelog = file("CHANGELOG.md").getText("UTF-8")
	displayName = "$project.version"
	gameVersions = ["1.20.1"]
	loaders = loom.platform.get().id()
	setVersion("$project.version")
	setArtifact(remapJar)
	addAdditionalFile(sourcesJar)
}

// configure the maven publication
publishing {
	publications {
		maven(MavenPublication) {
			from components.java
			pom {
				name = "LibGuiFoxified"
				description = "Minecraft GUI Library"
				url = "https://github.com/ThinkingStudios/LibGuiFoxified"
				licenses {
					license {
						name = "MIT"
						url = "https://github.com/ThinkingStudios/LibGuiFoxified/blob/HEAD/LICENSE"
					}
				}
				developers {
					developer {
						name = "ThinkingStudio"
						url = "https://github.com/ThinkingStudios"
					}
				}
			}
		}
	}

	// select the repositories you want to publish to
	repositories {
		maven {
			name = "cloudsmith"
			url = "https://maven.cloudsmith.io/thinkingstudio/libguifoxified/"
			def releasesRepoUrl = "https://maven.cloudsmith.io/thinkingstudio/libguifoxified/"
			def snapshotsRepoUrl = "https://maven.cloudsmith.io/thinkingstudio/libguifoxified/"
			url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
			credentials {
				username = 'tex-true'
				password = System.getenv("CLOUDSMITH_MAVEN_TOKEN")
			}
		}
	}
}
