plugins {
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
	id 'net.neoforged.moddev.legacyforge' version '2.0.78'
	id "com.hypherionmc.modutils.modpublisher" version "2.+"
}

base {
	archivesName = project.archives_base_name
}

version = "$project.mod_version+$project.minecraft_version"
group = project.maven_group

sourceSets {
	javadoc {
	}

//	testMod {
//		compileClasspath += main.compileClasspath
//		runtimeClasspath += main.runtimeClasspath
//	}
}

legacyForge {
	version = "1.20.1-47.3.0"
//	validateAccessTransformers = true
	parchment {
		minecraftVersion = '1.20.1'
		mappingsVersion = '2023.09.03'
	}

	runs {
		client {
			client()
		}
		data {
			data()
		}
		server {
			server()
		}
	}

	mods {
		testproject {
			sourceSet sourceSets.main
		}
	}
//	createRemapConfigurations(sourceSets.testMod)
//
//	runs {
//		testModClient {
//			client()
//			name = 'Test Mod Client'
//			source sourceSets.testMod
//		}
//
//		testModServer {
//			server()
//			name = 'Test Mod Server'
//			source sourceSets.testMod
//		}
//	}
}

// Work around https://github.com/FabricMC/fabric-loom/issues/890.
//afterEvaluate {
//	for (def config : [configurations.apiElements, configurations.runtimeElements]) {
//		def parents = new HashSet<>(config.extendsFrom)
//		parents.removeIf { it.name.startsWith 'modTestMod' }
//		config.extendsFrom = parents
//	}
//}

repositories {
	maven {
		url "https://server.bbkr.space/artifactory/libs-release"
		content {
			includeGroup "io.github.cottonmc"
		}
	}
	maven { url "https://jitpack.io" }
	maven { url "https://maven.su5ed.dev/releases" }
}

mixin {
	add sourceSets.main, 'mixins.libgui.refmap.json'
	config 'mixins.libgui.json' // This can be done for multiple configs
}

dependencies {
	implementation('org.jetbrains:annotations:24.0.1')

	implementation(jarJar("blue.endless:jankson:1.2.3"))
	compileOnly("blue.endless:jankson:1.2.3")
	runtimeOnly("blue.endless:jankson:1.2.3")
	jarJar api("com.github.TexBlock:LibNinePatch:master-SNAPSHOT")

	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
	// Test mod dependencies
//	testModImplementation sourceSets.main.output
}

processResources {
	inputs.property "version", project.version

	filesMatching("META-INF/mods.toml") {
		expand "version": project.version
	}
}

java {
	withSourcesJar()
	withJavadocJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile) {
	// ensure that the encoding is set to UTF-8, no matter what the system default is
	// this fixes some edge cases with special characters not displaying correctly
	// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
	options.encoding = "UTF-8"
	options.release.set 17
}

jar {
	from "CREDITS.txt", "LICENSE"
	manifest.attributes([
		"MixinConfigs": "mixins.libgui.json"
	])
}

def javadocBuildJar = tasks.register('javadocBuildJar', Jar) {
	destinationDirectory = file('build/devlibs')
	archiveClassifier = 'javadoc-build'
	from sourceSets.javadoc.output
}

javadoc {
	dependsOn javadocBuildJar

	options {
		links "https://maven.fabricmc.net/docs/yarn-$project.yarn_mappings"
		links 'https://javadoc.io/doc/org.jetbrains/annotations/19.0.0'
		taglets 'io.github.cottonmc.cotton.gui.jd.ExperimentalTaglet',
				'io.github.cottonmc.cotton.gui.jd.PropertyTaglet'
		tagletPath javadocBuildJar.get().archiveFile.get().asFile
	}

	exclude("**/impl/**")
}

publisher {
	apiKeys.modrinth(System.getenv("MODRINTH_TOKEN"))
	apiKeys.curseforge(System.getenv("CURSEFORGE_TOKEN"))

	curseID = "$project.curseforge_id"
	modrinthID = "$project.modrinth_id"
	versionType = "alpha"
	changelog = file("CHANGELOG.md").getText("UTF-8")
	displayName = "$project.archives_base_name"
	gameVersions = ["1.20.1"]
	loaders = "forge"
	setVersion("$project.version")
	setArtifact(reobfJar)
	addAdditionalFile(sourcesJar)
}

// configure the maven publication
publishing {
	publications {
		maven(MavenPublication) {
			from components.java
			pom {
				name = "LibGuiFoxified"
				description = "Minecraft GUI Library"
				url = "https://github.com/ThinkingStudios/LibGuiFoxified"
				licenses {
					license {
						name = "MIT"
						url = "https://github.com/ThinkingStudios/LibGuiFoxified/blob/HEAD/LICENSE"
					}
				}
				developers {
					developer {
						name = "ThinkingStudio"
						url = "https://github.com/ThinkingStudios"
					}
				}
			}
		}
	}

	// select the repositories you want to publish to
	repositories {
		maven {
			name = "cloudsmith"
			url = "https://maven.cloudsmith.io/thinkingstudio/libguifoxified/"
			def releasesRepoUrl = "https://maven.cloudsmith.io/thinkingstudio/libguifoxified/"
			def snapshotsRepoUrl = "https://maven.cloudsmith.io/thinkingstudio/libguifoxified/"
			url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
			credentials {
				username = 'tex-true'
				password = System.getenv("CLOUDSMITH_MAVEN_TOKEN")
			}
		}
	}
}
