# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = neoforge

# Fabric Properties
# check these on https://fabricmc.net/develop
	minecraft_version=1.21.1
	yarn_mappings=1.21.1+build.3
	neoforge_version=21.1.127
	yarn_patch=1.21+build.4

# Mod Properties
	upstream_version = 11.1.0
	mod_version = 0.1.0
	maven_group = org.thinkingstudio
	archives_base_name = LibGuiFoxified
	
