# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = neoforge

# Fabric Properties
# check these on https://fabricmc.net/develop
	minecraft_version=1.20.4
	yarn_mappings=1.20.4+build.3
	neoforge_version=20.4.239
	yarn_patch=1.20.4+build.4

# Mod Properties
	upstream_version = 10.0.0
	mod_version = 0.1.0
	maven_group = org.thinkingstudio
	archives_base_name = LibGuiFoxified

    curseforge_id=1211573
    modrinth_id=22KkUI0A
	
