modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "libgui"
version = "${version}"
displayName = "Libgui"
logoFile="icon.png"
authors="Falkreon,Juuz"

description = '''Easy grid-based GUIs for (Neo)Forge'''
[[dependencies.libgui]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.libgui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
