modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="libgui-test"
version="1.0.0"
displayName="Test Mod"
authors = "TexTrue, ThinkingStudio"
description="Some example Guis to shake out errors"
[[dependencies.libgui-test]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libgui-test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"
